# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UY7X6lh6Ch8lLODfaZWBhq9tqVbZxjMg
"""

!pip install pyspark

from pyspark import SparkConf, SparkContext
import collections
conf = SparkConf().setMaster("local").setAppName("word counting")
sc = SparkContext.getOrCreate(conf = conf)

from pyspark import SparkContext, SparkConf
conf = SparkConf().setMaster("local").setAppName("word counting")
sc = SparkContext.getOrCreate(conf = conf)

files = (sc.textFile('/content/text.txt').map(lambda line: line.split(' ')))
fileContent = files.reduce(lambda x: 1)
rdd = sc.parallelize(fileContent)
wrds = rdd.map(lambda word: (word, 1))
print("Số từ trong văn bản:", wrds.count())
red = wrds.reduceByKey(lambda x,y: x+y)
max = red.reduce(lambda x, y: x if x[1] > y[1] else y)
res = ', '.join(map(str, [x[0] for x in red.collect() if (x[1] == max[1])]))
print("Các từ '" + res + "' có tần suất xuất hiện nhiều nhất với " +str(max[1]) + " lần")